name: Deploy SAM Application

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials from GitHub Secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      # Build the SAM application
      - name: Build SAM application
        run: sam build

      # Package and deploy the SAM application
      - name: Deploy SAM application
        env:
          STACK_NAME: "nimo-sam-stack"  
          S3_BUCKET: "nimo-sam-deployment-bucket" 
        run: |
          # Package SAM application and upload artifacts to S3
          sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
          
          # Deploy SAM application
          sam deploy --template-file packaged.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM \
            --parameter-overrides "ParameterKey=CG_key,ParameterValue=${{ secrets.X_CG_API_KEY }}"
